#pragma once

#define Boss_MAX_HP 1000
#define Boss_SHIELD 1000
#define Boss_PROPERTIES PROPERTIES_LIGHT

#define ENEMY1_MAX_HP 50
#define ENEMY1_SHIELD 50
#define ENEMY1_PROPERTIES PROPERTIES_LIGHT

#define ENEMY2_MAX_HP 100
#define ENEMY2_SHIELD 100
#define ENEMY2_PROPERTIES PROPERTIES_LIGHT

#define REAL_DIE_TIMER 50


enum ENEMY_MODEww
{
	ENEMY_MODE_APPEARANCE = 0,

	ENEMY_MODE_STATE,

	ENEMY_MODE_MOVE,

	ENEMY_MODE_RUN_READY,
	ENEMY_MODE_RUN_STAY,
	ENEMY_MODE_RUN_END,

	ENEMY_MODE_NORMAL_ATT1,
	ENEMY_MODE_NORMAL_ATT2,
	ENEMY_MODE_NORMAL_ATT3,
	ENEMY_MODE_CLAW1,
	ENEMY_MODE_CLAW2,

	ENEMY_MODE_JUMP_SUCCESS,
	ENEMY_MODE_JUMP_FAIL,

	ENEMY_MODE_SPIT1,
	ENEMY_MODE_SPIT2,

	ENEMY_MODE_HIT_IDLE_HEAD_HEAVY_L,
	ENEMY_MODE_HIT_IDLE_HEAD_HEAVY_R,
	ENEMY_MODE_HIT_IDLE_HEAD_LIGHT_L,
	ENEMY_MODE_HIT_IDLE_HEAD_LIGHT_R,

	ENEMY_MODE_HIT_RUN_HEAD_HEAVY_L,
	ENEMY_MODE_HIT_RUN_HEAD_HEAVY_R,
	ENEMY_MODE_HIT_RUN_HEAD_LIGHT_L,
	ENEMY_MODE_HIT_RUN_HEAD_LIGHT_R,

	ENEMY_MODE_SPIT,

	ENEMY_MODE_AIR_ATT,
	ENEMY_MODE_MELEE_ATTACK,

	EYNEMY_MODE_BEAM_ATT,

	ENEMY_MODE_NULL,

	ENEMY_MODE_FINISH
};

enum ENEMY_PROPERTIES
{
	PROPERTIES_DARK, PROPERTIES_LIGHT, PROPERTIES_FIRE, PROPERTIES_WATER
};

enum SKAG_MODE
{
	UNIT_NORMAL, UNIT_SPITTER, UNIT_ALPHA, UNIT_SKAGZILLA
};

struct Enemy_Stat
{
	int						Hp;							//À¯´Ö Ã¼·Â
	int						Max_Hp;						//À¯´Ö ¸Æ½ºÃ¼·Â
	int						shield;						//À¯´Ö ½Çµå
	int						Max_shield;					//À¯´Ö ¸Æ½º½Çµå
	int						Properties;					//À¯´Ö ¼Ó¼º
	bool					LiveOrDie;					//À¯´ÖÀÌ Á×°í Ã¤·ÂÀÌ ´Ù µÇ¾î deleteµÇ¾î¾ßÇÏ´Â°¡(true == live)
	bool                    F_ok;
};